import { Inter } from 'next/font/google'
import './globals.css'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import { getServerSession } from 'next-auth'
import Home from './page'
import SessionProvider from './SessionProvider'
import SignIn from './auth/signin/page'
import Dashboard from './dashboard/page'

const inter = Inter({ subsets: ['latin'] })

/*
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
*/

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ? (
            <SignIn />
          ) : (
            <Dashboard />
          )}
        </SessionProvider>
      </body>
    </html>
  )
}
